# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'game_view.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_game_dialog(object):
    def setupUi(self, game_dialog):
        game_dialog.setObjectName("game_dialog")
        game_dialog.resize(800, 600)
        self.frame = QtWidgets.QFrame(game_dialog)
        self.frame.setGeometry(QtCore.QRect(80, 50, 601, 511))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(20, 430, 371, 41))
        self.progressBar.setMaximum(12)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(460, 350, 141, 121))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(90, 10, 41, 41))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/TriviaDemo/Trivia-Simulator/UI/resources/Correct.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 60, 41, 41))
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:/TriviaDemo/Trivia-Simulator/UI/resources/Incorrect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.right_answers = QtWidgets.QLabel(self.frame_2)
        self.right_answers.setGeometry(QtCore.QRect(40, 10, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Guttman Yad-Brush")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(True)
        self.right_answers.setFont(font)
        self.right_answers.setAlignment(QtCore.Qt.AlignCenter)
        self.right_answers.setObjectName("right_answers")
        self.wrong_answers = QtWidgets.QLabel(self.frame_2)
        self.wrong_answers.setGeometry(QtCore.QRect(40, 60, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Guttman Yad-Brush")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(True)
        self.wrong_answers.setFont(font)
        self.wrong_answers.setAlignment(QtCore.Qt.AlignCenter)
        self.wrong_answers.setObjectName("wrong_answers")
        self.timer = QtWidgets.QLCDNumber(self.frame)
        self.timer.setGeometry(QtCore.QRect(500, 30, 64, 41))
        self.timer.setProperty("value", 10.0)
        self.timer.setObjectName("timer")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(20, 30, 441, 371))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.question_label = QtWidgets.QLabel(self.frame_3)
        self.question_label.setGeometry(QtCore.QRect(30, 10, 391, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.question_label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Guttman Yad-Brush")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.question_label.setFont(font)
        self.question_label.setIndent(10)
        self.question_label.setObjectName("question_label")
        self.line = QtWidgets.QFrame(self.frame_3)
        self.line.setGeometry(QtCore.QRect(0, 70, 441, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.line.setFont(font)
        self.line.setLineWidth(6)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.answer1 = QtWidgets.QPushButton(self.frame_3)
        self.answer1.setGeometry(QtCore.QRect(10, 90, 411, 61))
        font = QtGui.QFont()
        font.setFamily("Guttman Yad-Brush")
        font.setPointSize(13)
        self.answer1.setFont(font)
        self.answer1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.answer1.setDefault(True)
        self.answer1.setFlat(False)
        self.answer1.setObjectName("answer1")
        self.answer4 = QtWidgets.QPushButton(self.frame_3)
        self.answer4.setGeometry(QtCore.QRect(10, 300, 411, 61))
        font = QtGui.QFont()
        font.setFamily("Guttman Yad-Brush")
        font.setPointSize(13)
        self.answer4.setFont(font)
        self.answer4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.answer4.setDefault(True)
        self.answer4.setFlat(False)
        self.answer4.setObjectName("answer4")
        self.answer3 = QtWidgets.QPushButton(self.frame_3)
        self.answer3.setGeometry(QtCore.QRect(10, 230, 411, 61))
        font = QtGui.QFont()
        font.setFamily("Guttman Yad-Brush")
        font.setPointSize(13)
        self.answer3.setFont(font)
        self.answer3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.answer3.setDefault(True)
        self.answer3.setFlat(False)
        self.answer3.setObjectName("answer3")
        self.answer12 = QtWidgets.QPushButton(self.frame_3)
        self.answer12.setGeometry(QtCore.QRect(10, 160, 411, 61))
        font = QtGui.QFont()
        font.setFamily("Guttman Yad-Brush")
        font.setPointSize(13)
        self.answer12.setFont(font)
        self.answer12.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.answer12.setDefault(True)
        self.answer12.setFlat(False)
        self.answer12.setObjectName("answer12")

        self.retranslateUi(game_dialog)
        QtCore.QMetaObject.connectSlotsByName(game_dialog)

    def retranslateUi(self, game_dialog):
        _translate = QtCore.QCoreApplication.translate
        game_dialog.setWindowTitle(_translate("game_dialog", "Dialog"))
        self.right_answers.setText(_translate("game_dialog", "0"))
        self.wrong_answers.setText(_translate("game_dialog", "0"))
        self.question_label.setText(_translate("game_dialog", "שאלה...."))
        self.answer1.setText(_translate("game_dialog", "תשובה א"))
        self.answer4.setText(_translate("game_dialog", "תשובה א"))
        self.answer3.setText(_translate("game_dialog", "תשובה א"))
        self.answer12.setText(_translate("game_dialog", "תשובה א"))
